### ISSUE TITLE
Duplicate field @timestamp

### ISSUE THREAD

**Issue by ml-jzimmermann** [eBay/nvidiagpubeat#11]
Hi thanks for the great work so far. 

The beater creates the field @timestamp twice which raises: mapper_parsing_exception with reason: failed to parse caused by: Duplicate field @timestamp.

Can you change the output fields or show a way to handle this in elasticsearch / kibana?

Regards,
Julius

**Comment by deepujain** [comment]
Hello Julius (@ca3sa4),
Thanks for using nvidiagpubeat. Good catch on @timestamp. 

PR https://github.com/eBay/nvidiagpubeat/pull/12/ should address the issue. 

@ca3sa4 
I have included a testimonial section (close to end of file) in Readme.md. When you find time, please share few words about your use case and submit a PR.
Regards,
Deepak

**Comment by deepujain** [comment]
@ca3sa4 I will leave this Issue open and wait for you to verify the fix.

**Comment by ml-jzimmermann** [comment]
Hi, the @timestamp field is sent only once now, but it is recognised as type string in elasticsearch. in the meantime i have setup a logstash pipeline to parse and map the outputs of nvidiagpubeat. for me, this will do it for now.

Thanks for the help,
Julius
