### ISSUE TITLE
Documentation for build in Linux environment

### ISSUE THREAD

**Issue by deepujain** [eBay/nvidiagpubeat#3]
Update Readme with pre-requisite steps for building in Linux environment.

**Comment by minduni** [comment]
Here the steps to build the nvidiagpubeat binary on a RedHat ES 7.3:

- Software requirements installation
```
yum install python-virtualenv
yum install golang
```

- Actual  build of the executable
```
cd ~   
mkdir beats_dev 
export WORKSPACE=`pwd`/beats_dev
export GOPATH=$WORKSPACE
git clone https://github.com/elastic/beats ${GOPATH}/src/github.com/elastic/beats --branch 6.5
mkdir $WORKSPACE/src/github.com/deepujain
cd $WORKSPACE/src/github.com/deepujain
git clone https://github.com/deepujain/nvidiagpubeat
cd nvidiagpubeat/
make copy-vendor
make
```

**Comment by deepujain** [comment]
@minduni Thanks for the steps. eBay repository no longer uses "deepujain".

Could you please give a PR for README.md . Also, clearly indicate that the executable was indeed built after the steps ( ls -l )

**Comment by deepujain** [comment]
Updated.
